import { sql } from "drizzle-orm";
import {
  index,
  integer,
  sqliteTable,
  text,
  uniqueIndex,
  type AnySQLiteColumn,
} from "drizzle-orm/sqlite-core";
import {
  IDENTITY_PROVIDERS,
  LEVELS,
  ORIGIN_PROVIDERS,
  PRIORITIES,
  REQUEST_EVENT_TYPES,
  REQUEST_LINK_TYPES,
  REQUEST_SOURCE_TYPES,
  REQUEST_STATUSES,
  USER_ROLES,
} from "@prh/shared";

// SQLite (Cloudflare D1) has no native enum/uuid/timestamp/jsonb types:
//   - enums are TEXT columns typed by their value lists (validated by zod at the API boundary)
//   - ids are UUID strings generated by the application
//   - timestamps are epoch milliseconds (mapped to Date)
//   - json is TEXT mapped to objects

const id = () =>
  text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID());

const createdAt = () =>
  integer("created_at", { mode: "timestamp_ms" })
    .notNull()
    .$defaultFn(() => new Date());

const timestamps = {
  createdAt: createdAt(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .notNull()
    .$defaultFn(() => new Date())
    .$onUpdate(() => new Date()),
};

const json = (name: string) =>
  text(name, { mode: "json" }).$type<Record<string, unknown>>().notNull().default(sql`'{}'`);

export const workspaces = sqliteTable("workspaces", {
  id: id(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  ...timestamps,
});

export const projects = sqliteTable(
  "projects",
  {
    id: id(),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id),
    name: text("name").notNull(),
    slug: text("slug").notNull(),
    isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
    ...timestamps,
  },
  (t) => [uniqueIndex("projects_workspace_slug_key").on(t.workspaceId, t.slug)],
);

export const users = sqliteTable(
  "users",
  {
    id: id(),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id),
    name: text("name").notNull(),
    email: text("email"),
    role: text("role", { enum: USER_ROLES }).notNull().default("requester"),
    ...timestamps,
  },
  (t) => [uniqueIndex("users_workspace_email_key").on(t.workspaceId, t.email)],
);

/** Discord user IDs, GitHub logins... are kept out of `users`. */
export const externalIdentities = sqliteTable(
  "external_identities",
  {
    id: id(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    provider: text("provider", { enum: IDENTITY_PROVIDERS }).notNull(),
    externalUserId: text("external_user_id").notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    // One identity per provider per user. The same Discord account may map to
    // users in several workspaces, so (provider, external_user_id) is not unique.
    uniqueIndex("external_identities_user_provider_key").on(t.userId, t.provider),
    index("external_identities_provider_external_idx").on(t.provider, t.externalUserId),
  ],
);

export const discordIntegrations = sqliteTable("discord_integrations", {
  id: id(),
  workspaceId: text("workspace_id")
    .notNull()
    .references(() => workspaces.id),
  name: text("name"),
  discordGuildId: text("discord_guild_id").notNull().unique(),
  status: text("status", { enum: ["active", "disabled"] })
    .notNull()
    .default("active"),
  ...timestamps,
});

export const discordChannelMappings = sqliteTable(
  "discord_channel_mappings",
  {
    id: id(),
    integrationId: text("integration_id")
      .notNull()
      .references(() => discordIntegrations.id, { onDelete: "cascade" }),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    discordGuildId: text("discord_guild_id").notNull(),
    discordChannelId: text("discord_channel_id").notNull(),
    requestEnabled: integer("request_enabled", { mode: "boolean" }).notNull().default(true),
    ...timestamps,
  },
  (t) => [
    uniqueIndex("discord_channel_mappings_guild_channel_key").on(
      t.discordGuildId,
      t.discordChannelId,
    ),
  ],
);

export const releases = sqliteTable(
  "releases",
  {
    id: id(),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    name: text("name").notNull(),
    releasedAt: integer("released_at", { mode: "timestamp_ms" }),
    ...timestamps,
  },
  (t) => [uniqueIndex("releases_project_name_key").on(t.projectId, t.name)],
);

/** Per-workspace counter backing REQ-0001, REQ-0002, ... */
export const requestNumberSequences = sqliteTable("request_number_sequences", {
  workspaceId: text("workspace_id")
    .primaryKey()
    .references(() => workspaces.id),
  lastNumber: integer("last_number").notNull().default(0),
});

export const requests = sqliteTable(
  "requests",
  {
    id: id(),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    requestNumber: integer("request_number").notNull(),
    title: text("title").notNull(),
    description: text("description").notNull(),
    status: text("status", { enum: REQUEST_STATUSES }).notNull().default("new"),
    priority: text("priority", { enum: PRIORITIES }),
    impact: text("impact", { enum: LEVELS }),
    effort: text("effort", { enum: LEVELS }),
    requesterId: text("requester_id").references(() => users.id),
    assigneeId: text("assignee_id").references(() => users.id),
    targetReleaseId: text("target_release_id").references(() => releases.id),
    duplicateOfId: text("duplicate_of_id").references((): AnySQLiteColumn => requests.id),
    sourceProvider: text("source_provider", { enum: ORIGIN_PROVIDERS }).notNull(),
    ...timestamps,
    releasedAt: integer("released_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    uniqueIndex("requests_workspace_number_key").on(t.workspaceId, t.requestNumber),
    index("requests_workspace_status_idx").on(t.workspaceId, t.status),
    index("requests_project_idx").on(t.projectId),
    index("requests_duplicate_of_idx")
      .on(t.duplicateOfId)
      .where(sql`${t.duplicateOfId} is not null`),
  ],
);

/** Where a request was filed (Discord message, Slack thread, web form...). */
export const requestOrigins = sqliteTable(
  "request_origins",
  {
    id: id(),
    requestId: text("request_id")
      .notNull()
      .references(() => requests.id, { onDelete: "cascade" }),
    provider: text("provider", { enum: ORIGIN_PROVIDERS }).notNull(),
    externalWorkspaceId: text("external_workspace_id"),
    externalChannelId: text("external_channel_id"),
    externalMessageId: text("external_message_id"),
    externalThreadId: text("external_thread_id"),
    externalUrl: text("external_url"),
    metadata: json("metadata"),
    createdAt: createdAt(),
  },
  (t) => [index("request_origins_request_idx").on(t.requestId)],
);

/** One row per real occurrence of the demand. Request count = COUNT(request_sources). */
export const requestSources = sqliteTable(
  "request_sources",
  {
    id: id(),
    requestId: text("request_id")
      .notNull()
      .references(() => requests.id, { onDelete: "cascade" }),
    sourceType: text("source_type", { enum: REQUEST_SOURCE_TYPES }),
    userId: text("user_id").references(() => users.id),
    externalUserId: text("external_user_id"),
    note: text("note"),
    createdAt: createdAt(),
  },
  (t) => [index("request_sources_request_idx").on(t.requestId)],
);

/** Development artifacts linked to a request (GitHub Issue / PR / Release). */
export const requestLinks = sqliteTable(
  "request_links",
  {
    id: id(),
    requestId: text("request_id")
      .notNull()
      .references(() => requests.id, { onDelete: "cascade" }),
    linkType: text("link_type", { enum: REQUEST_LINK_TYPES }).notNull(),
    url: text("url").notNull(),
    label: text("label"),
    createdById: text("created_by_id").references(() => users.id),
    createdAt: createdAt(),
  },
  (t) => [index("request_links_request_idx").on(t.requestId)],
);

/**
 * Activity timeline and audit log. Append-only.
 * Events are read back ordered by (created_at, rowid): rowid is monotonic for an
 * insert-only table, so events written within the same millisecond keep their order.
 */
export const requestEvents = sqliteTable(
  "request_events",
  {
    id: id(),
    requestId: text("request_id")
      .notNull()
      .references(() => requests.id, { onDelete: "cascade" }),
    actorUserId: text("actor_user_id").references(() => users.id),
    eventType: text("event_type", { enum: REQUEST_EVENT_TYPES }).notNull(),
    oldValue: text("old_value"),
    newValue: text("new_value"),
    metadata: json("metadata"),
    createdAt: createdAt(),
  },
  (t) => [index("request_events_request_idx").on(t.requestId, t.createdAt)],
);
