import { bindings, defineConfig } from "cf/config";

// Generated by `cf migrate` from wrangler.jsonc (cf CLI, open beta).
// wrangler.jsonc is kept: `wrangler types`, the D1 migration scripts and tests still
// read it. Until they move to cf, change both files together.
// D1 `migrations_dir` ("../../packages/database/migrations") is passed to the
// migration scripts as a flag; cf does not keep it in config.

export default defineConfig({
	worker: {
		name: "product-request-hub-api",
		compatibilityDate: "2025-09-01",
		compatibilityFlags: [
			"nodejs_compat",
		],
		entrypoint: "src/index.ts",
		observability: {
			enabled: true,
		},
		env: {
			WEB_BASE_URL: bindings.text("https://product-request-hub-web.tomoki-ttttt.workers.dev"),
			CF_ACCESS_TEAM_DOMAIN: bindings.text("tomoki-ttttt.cloudflareaccess.com"),
			CF_ACCESS_AUD: bindings.text("c02841484d0af4ab8f318553ced2464fd998a3fd8b9f781a6edd18b76e4257f0"),
			DB: bindings.d1({
				name: "product-request-hub",
				id: "5df255d3-5631-43d9-a3e5-624dba61f99b",
			}),
		},
	},
});
